name: Deploy Backend and Frontend on Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy na VM Oracle Cloud
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            export PATH="/home/ubuntu/.nvm/versions/node/v24.16.0/bin:$PATH"

            cd ~/T5.1

            echo "Atualizando repositório..."
            git fetch
            git pull origin main

            echo "Instalando dependências do backend..."

            cd ~/T5.1/backend

            if [ ! -d ".venv" ]; then
              python3 -m venv .venv
            fi

            .venv/bin/python -m pip install --upgrade pip

            if [ -f requirements.txt ]; then
              .venv/bin/pip install -r requirements.txt
            fi

            if [ -f requirements-dev.txt ]; then
              .venv/bin/pip install -r requirements-dev.txt
            fi

            echo "Executando testes do backend..."
            .venv/bin/pytest -q

            echo "Instalando dependências do Admin Parametrização..."

            cd ~/T5.1/frontend/admin-parametrizacao

            npm install

            echo "Executando testes..."
            npm run test

            echo "Instalando dependências do Meus Vídeos..."

            cd ~/T5.1/frontend/meus-videos

            npm install

            echo "Executando testes..."
            npm run test

            echo "Todos os testes passaram!"

            echo "Reiniciando backend..."
            sudo systemctl restart fastapi

            echo "Gerando build do Admin Parametrização..."
            cd ~/T5.1/frontend/admin-parametrizacao
            npm run build

            echo "Gerando build do Meus Vídeos..."
            cd ~/T5.1/frontend/meus-videos
            npm run build

            echo "Deploy concluído com sucesso!"
