name: Deploy Backend and Frontend on Oracle Cloud

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    # garante que só roda se o PR foi realmente mergeado
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - name: Deploy na VM Oracle Cloud
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "Adiciona localização do npm no shell atual"
            export PATH="/home/ubuntu/.nvm/versions/node/v24.16.0/bin:$PATH"

            cd ~/T5.1

            echo "Atualiza repositório"
            git fetch
            git pull origin main

            echo "Reinicia backend"
            sudo systemctl restart fastapi

            echo "Atualiza build do frontend parametrizacao"
            cd ~/T5.1/frontend/admin-parametrizacao
            npm run build

            echo "Atualiza build do frontend meus videos"
            cd ~/T5.1/frontend/meus-videos
            npm run build

            echo "Deploy concluído!"
